repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-toml
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.6.8
    hooks:
      - id: uv-lock
      - id: uv-export
      - id: pip-compile
        args: [requirements-dev.in, -o, requirements-dev.txt]
        files: ^requirements-dev\.(in|txt)$
  - repo: https://github.com/quantco/pre-commit-mirrors-ruff
    rev: 0.4.3
    hooks:
      - id: ruff-conda
      - id: ruff-format-conda
  - repo: https://github.com/quantco/pre-commit-mirrors-mypy
    rev: 1.10.0
    hooks:
      - id: mypy-conda
